CREATE TABLE IF NOT EXISTS file_download_audit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    audit_no VARCHAR(64) NOT NULL COMMENT '审计编号',
    request_id VARCHAR(64) DEFAULT NULL COMMENT '请求ID',
    action VARCHAR(32) NOT NULL COMMENT '行为类型：CREATE_TOKEN/DOWNLOAD_FILE',
    download_status VARCHAR(32) NOT NULL COMMENT '下载结果状态',
    fail_reason VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
    file_no VARCHAR(64) DEFAULT NULL COMMENT '文件编号',
    file_name VARCHAR(255) DEFAULT NULL COMMENT '文件名称',
    file_type VARCHAR(32) DEFAULT NULL COMMENT '文件类型',
    settle_date DATE DEFAULT NULL COMMENT '结算日期',
    member_id VARCHAR(32) DEFAULT NULL COMMENT '会员编号',
    version INT DEFAULT NULL COMMENT '文件版本',
    client_ip VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
    user_agent VARCHAR(512) DEFAULT NULL COMMENT 'User-Agent',
    token_digest VARCHAR(128) DEFAULT NULL COMMENT 'Token摘要，不保存完整Token',
    file_size BIGINT DEFAULT NULL COMMENT '文件大小',
    download_bytes BIGINT DEFAULT NULL COMMENT '实际下载字节数',
    start_time DATETIME DEFAULT NULL COMMENT '下载开始时间',
    end_time DATETIME DEFAULT NULL COMMENT '下载结束时间',
    cost_ms BIGINT DEFAULT NULL COMMENT '下载耗时毫秒',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_audit_no (audit_no),
    KEY idx_member_date (member_id, settle_date),
    KEY idx_file_no (file_no),
    KEY idx_status_created (download_status, created_at),
    KEY idx_client_ip_created (client_ip, created_at),
    KEY idx_created_at (created_at)
) COMMENT='文件下载审计表';
