server.port=${SETTLE_AUDIT_SERVICE_PORT:8106}

spring.application.name=settle-audit-service
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR:localhost:8848}

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3307/exchange_clear?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never

mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.wuxx.exchangeclear
mybatis.configuration.map-underscore-to-camel-case=true

rocketmq.name-server=${ROCKETMQ_NAME_SERVER:localhost:9876}
rocketmq.consumer.group=${ROCKETMQ_DOWNLOAD_AUDIT_CONSUMER_GROUP:exchange-clear-download-audit-consumer-group}

exchange-clear.mq.topic.download-audit=${EXCHANGE_CLEAR_MQ_DOWNLOAD_AUDIT_TOPIC:file-download-audit}
exchange-clear.mq.consumer-group.download-audit=${EXCHANGE_CLEAR_MQ_DOWNLOAD_AUDIT_CONSUMER_GROUP:exchange-clear-download-audit-consumer-group}
